/*
 * MIT License
 *
 * Copyright (c) 2022 Git-an-A
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package team.project;

import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Labeled;
import javafx.stage.Stage;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.testfx.api.FxAssert;
import org.testfx.api.FxRobot;
import org.testfx.framework.junit5.ApplicationExtension;
import org.testfx.framework.junit5.Start;
import org.testfx.matcher.control.LabeledMatchers;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(ApplicationExtension.class)
public class AppTest {
    private Scene scene;
    Stage testStage;
    @Start
    private void start(Stage stage) throws Exception {
        App app = new App();
        app.start(stage);
        scene = stage.getScene();
        testStage = stage;
    }
    @Test
    void testStart() {
        Parent parent = scene.getRoot();
        assertEquals("Acquire", testStage.getTitle());
        Node node = parent.getChildrenUnmodifiable().get(0);
        FxAssert.verifyThat((Labeled) node, LabeledMatchers.hasText("New Game"));
        node = parent.getChildrenUnmodifiable().get(1);
        FxAssert.verifyThat((Labeled) node, LabeledMatchers.hasText("Load Game"));
        node = parent.getChildrenUnmodifiable().get(2);
        FxAssert.verifyThat((Labeled) node, LabeledMatchers.hasText("Start!"));
        node = parent.getChildrenUnmodifiable().get(3);
        FxAssert.verifyThat((Labeled) node, LabeledMatchers.hasText("Quit"));
        node = parent.getChildrenUnmodifiable().get(4);
        FxAssert.verifyThat((Labeled) node, LabeledMatchers.hasText("Welcome to Acquire!"));
    }
}
