/*
 * MIT License
 *
 * Copyright (c) 2022 Git-an-A
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package team.project;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

public class App extends Application{

    public static void main(String[] args) {
        Application.launch(args);
        System.out.println("test");
    }

    @Override
    public void start(Stage stage) throws Exception {

        stage.setTitle("Aquire");

        Group root = new Group();
        Scene scene = new Scene(root, 450, 400);
        scene.setFill(Color.LIGHTGRAY);

        RadioButton newGame = new RadioButton();
        RadioButton loadGame = new RadioButton();
        Button start = new Button();
        Button quit = new Button();
        Label title = new Label();

        final int buttonSpacing = 25;

        final int newGameXloc = 300;
        final int newGameYloc = 200;
        final int loadGameXloc = newGameXloc;
        final int loadGameYloc = newGameYloc + buttonSpacing;
        final int startXloc = 325;
        final int startYloc = 250;
        final int quitXloc = startXloc;
        final int quitYloc = startYloc + buttonSpacing;
        final int titleXloc = 75;
        final int titleYloc = 85;


        newGame.setLayoutX(newGameXloc);
        newGame.setLayoutY(newGameYloc);
        loadGame.setLayoutX(loadGameXloc);
        loadGame.setLayoutY(loadGameYloc);
        start.setLayoutX(startXloc);
        start.setLayoutY(startYloc);
        quit.setLayoutX(quitXloc);
        quit.setLayoutY(quitYloc);
        title.setLayoutX(titleXloc);
        title.setLayoutY(titleYloc);

        root.getChildren().add(newGame);
        root.getChildren().add(loadGame);
        root.getChildren().add(start);
        root.getChildren().add(quit);
        root.getChildren().add(title);

        stage.setResizable(false);
        stage.setScene(scene);
        stage.show();
    }


}
