# This workflow is based off of the starter workflow
# This workflow will build and test the project with gradle and cache/restore any dependencies to improve the workflow execution time


name: Java CI with Gradle

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Make gradlew executable
      run: chmod +x gradlew
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - name: license Main
      run: .gradlew licenseMain
    - name: license Test
      run: .gradlew licenseTest
    - name: javadoc
      run: .gradlew javadoc
    - name: Jacoco report
      run: .gradlew jacocoTestReport
 

