# This workflow is based off of the GitHub Actions Docs
# This workflow will test when wanting to pull and push

name: Testing on Push and Pull

on: [pull_request]

jobs:
  test:
    name: GradleTest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      - name: Test
        run: ./gradlew test --tests "*"

#      - name: Test Success
#        if: success()
#        uses: actions/github-script@v6
#        with:
#          github-token: ${{ github.token }}
#          script: |
#            const pull_number = "${{github.event.number}}"
#            await github.pulls.createReview({
#              ...context.repo,
#              pull_number,
#              body: "All tests passed.",
#              event: "APPROVE"
#            })
#      - name: Test Fail
#        if: failure()
#        uses: actions/github-script@v6
#        with:
#          github-token: ${{ github.token }}
#          script: |
#            const pull_number = "${{github.event.number}}"
#            await github.pulls.createReview({
#              ...context.repo,
#              pull_number,
#              body: "There is something wrong with test codes.",
#             event: "REQUEST_CHANGES"
#            })
#            await github.pulls.update({
#              ...context.repo,
#              pull_number,
#              state: "closed"
#            })
